# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: double-quote-string-fixer
    -   id: debug-statements
    -   id: check-toml
    -   id: check-json
    -   id: check-xml
-   repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
    -   id: markdown-link-check
        name: ensure-lint
-   repo: local
    hooks:
    -   id: ensure-code
        name: ensure-code
        entry: bash -c 'make test-code'
        language: system
